### ISSUE TITLE
Multi Pickup Config - Pickup Distance From Bridge not editable

### ISSUE THREAD

**Issue by eleanorfontaine** [cycfi/ascend#1]
EDIT: Fixed with FX -> Send all keyboard input to plugin

Reaper v6.15, Win64

Pickup Distance from Bridge Value locked at default (3.21cm) value.

**Comment by djowel** [comment]
Fixed now with the Ascend VPU v1.0-eval-1c update. No need for FX -> Send all keyboard input to plugin. Also fixes Ableton-live on windows.
