### ISSUE TITLE
Suggestion: Prompt for string tuning on first plugin load per instance

### ISSUE THREAD

**Issue by eleanorfontaine** [cycfi/ascend#14]
The plugin could open a prompt window with "What tuning is this string" and possibly how far the pickup is from the bridge when opened for the first time in a given instance of the plugin, with a checkmark box to turn off the prompt. This would prevent people from not realizing they need to manually set their tuning for the plugin to operate correctly.

Maybe also have it generate a reference pitch tone after you enter a note so that people don't enter the wrong octave of tuning?

Also, maybe have an option nested away for hz offset for microtonal tunings.

**Comment by djowel** [comment]
Actually, the ideal (non-lazy) way is to pitch detect. E.g. an ear icon can listen to the channel, you play the lowest note, and it sets it for you. I'll get to it when I have more time.

**Comment by djowel** [comment]
Here:

<img width="912" alt="Screen Shot 2021-01-20 at 1 31 29 AM" src="https://user-images.githubusercontent.com/568094/105071733-ef00ea00-5abf-11eb-91c6-7cff38d78b41.png">

Now the UI is cleaner!

**Comment by djowel** [comment]
Fixed now (will be in the next eval release 1g)
