### ISSUE TITLE
Suggestion: Mouse shortcuts

### ISSUE THREAD

**Issue by eleanorfontaine** [cycfi/ascend#2]
The immediate intuitive thing that I did when I first loaded up the plugin is double click on the pickup graphic to see if it would enable or disable it. Here are some idea for mouse shortcuts when mouse is over a given pickup:

Double click: pickup I/O
Middle mouse click: phase invert
Right mouse click: cycle between single/double coil
Scroll wheel: Pickup volume
Shift+left click and drag: LPF
Shift+Middle click and drag: HPF
Shift+right click and drag: Q

**Comment by cycfi** [comment]
> The immediate intuitive thing that I did when I first loaded up the plugin is double click on the pickup graphic to see if it would enable or disable it. Here are some idea for mouse shortcuts when mouse is over a given pickup:

Wow. Nice suggestions!

**Comment by djowel** [comment]
Here's a revised scheme with consistent cross-platform behavior in mind. E.g Mac does not normally have the middle button and scroll-wheel behaves differently in windows and the mac.

Double click: pickup I/O
Shift + Double click: phase invert
Option + Double click: toggle single/double coil
Shift + drag vertical: Pickup volume (relative movement)
Shift + drag horizontal: LPF (relative movement)
Option + drag vertical: Q (relative movement)
Option + drag horizontal: HPF (relative movement)

**Comment by djowel** [comment]
Oh and BTW, in case this is not documented:

Option + click: reset pickup slant

**Comment by djowel** [comment]
Change strategy. It's too easy to move Q when moving volume.

Double click: pickup I/O
Shift + double click: phase invert
Option + double click: toggle single/double coil
Shift + drag: Pickup volume (relative movement)
Option + drag: LPF (relative movement)
Shift + Option + drag: Q (relative movement)

I'm removing the shortcuts for HPF. IMO, it's are not as frequently used as vol, freq and Q. After all, the control for that is just few pixels away.

**Comment by djowel** [comment]
OK this is done. This will make it into eval-1f (next revision)

**Comment by musicbynumbers** [comment]
Tested and all working great so far thanks!
