### ISSUE TITLE
Issue: "About Ascent VPU" hanging

### ISSUE THREAD

**Issue by eleanorfontaine** [cycfi/ascend#4]
Reaper v6.18 Win64

The graphic display for the "About Ascend VPU" doesn't go away when it's done and makes groups and positions not useable.

**Comment by cycfi** [comment]
> The graphic display for the "About Ascend VPU" doesn't go away when it's done and makes groups and positions not useable.

With FX-> send all keyboard input to plugin, it should go away on "escape" keypress. But I should probably just close it after a few secs, instead of having it linger there indefinitely.

**Comment by djowel** [comment]
This should be fixed now in the latest updates, esp. eval-1d
