### ISSUE TITLE
AU plug-in failed in Logic Pro X

### ISSUE THREAD

**Issue by spjnowak** [cycfi/ascend#6]
I installed the AU in Logic Pro X v10.5.1 on a MacBook Pro 13" (MacOS Mojave 10.14.6) and got a validation error on starting up Logic Pro.
validating Audio Unit Ascend Multichannel Effects Processor by Cycfi Research:

    AU Validation Tool
    Version: 1.6.1a1 
    Copyright 2003-2013, Apple Inc. All Rights Reserved.
    Specify -h (-help) for command options

--------------------------------------------------
VALIDATING AUDIO UNIT: 'aufx' - 'owqo' - 'Cycf'
--------------------------------------------------
Manufacturer String: Cycfi Research
AudioUnit Name: Ascend Multichannel Effects Processor
Component Version: 1.0.0 (0x10000)

* * PASS
--------------------------------------------------
TESTING OPEN TIMES:
COLD:
FATAL ERROR: OpenAComponent: result: -1,0xFFFFFFFF

validation result: couldn’t be opened

**Comment by cycfi** [comment]
Hmmm... Mojave. Probably because I am using the latest APIs on Catalina. I should maybe switch back a little bit. I'll see what I can do, maybe run a virtual machine with Mojave or even older. Meantime, is there a way for you to test on Catalina?

**Comment by spjnowak** [comment]
Hi Joel

I thought it might need Catalina. I haven’t upgraded as I wanted to maintain compatibility with 16-bit apps. Maybe I should try the VST version?

Stefan (Snow Black)

Sent from my iPhone

On 11 Dec 2020, at 00:37, Cycfi Research <notifications@github.com> wrote:

﻿
Hmmm... Mojave. Probably because I am using the latest APIs on Catalina. I should maybe switch back a little bit. I'll see what I can do, maybe run a virtual machine with Mojave or even older. Meantime, is there a way for you to test on Catalina?

**Comment by djowel** [comment]
> I thought it might need Catalina. I haven’t upgraded as I wanted to maintain compatibility with 16-bit apps. Maybe I should try the VST version? Stefan (Snow Black)

Hold on a bit.... I am trying to figure this out. Actually, it might be more difficult with Catalina since code signing is now required. It might be easier for me to support Mojave, actually. I installed a VM and installing Xcode there for dev. We shall see...

**Comment by djowel** [comment]
> to maintain compatibility with 16-bit apps

I suppose you mean 32 bit apps? ;-)

**Comment by spjnowak** [comment]
Oops! Yes 32-bit not 16 (showing my age there!) 🧔🏼

Sent from my iPhone

On 11 Dec 2020, at 09:32, Joel de Guzman <notifications@github.com> wrote:

﻿
to maintain compatibility with 16-bit apps

I suppose you mean 32 bit apps? ;-)

**Comment by djowel** [comment]
OK, I uploaded a re-built version that targets at least MacOS 10.10. I can verify that it passes auval on Mojave. Please give it a try.

I also uploaded a rebuild of the VST3 plugin on MacOS. Now targeting at least MacOS 10.10.

**Comment by djowel** [comment]
Ascend VPU v1.0-eval-1b is available now. Hopefully this fixes your Mojave issues. Tested on Mojave myself.

**Comment by djowel** [comment]
@spjnowak can you verify that this the new updates fixes your Mojave issues, so I can close this now?

**Comment by spjnowak** [comment]
Yes I think all is OK now, thanks 🙏 

Sent from my iPhone

On 9 Jan 2021, at 04:46, Joel de Guzman <notifications@github.com> wrote:

﻿
@spjnowak can you verify that this the new updates fixes your Mojave issues, so I can close this now?

**Comment by djowel** [comment]
> Yes I think all is OK now, thanks 🙏

Great. Thanks! I'll close this issue now.
