### ISSUE TITLE
Lower the A1 Limit

### ISSUE THREAD

**Issue by FelixAhl** [cycfi/ascend#7]
For 8-string players who tune lower, setting the lower limit to E1 would be much appreciated and helpful in evaluating the plugin.

**Comment by djowel** [comment]
Implemented. This will make it to eval-1f. But please take note that, although it is in most part backward compatible with the previous saved sessions, you will have to re-set the Base note for ongoing DAW sessions with this update.

**Comment by djowel** [comment]
Oh, and the limit is now C1 to B4.

**Comment by FelixAhl** [comment]
That’s fantastic! I’ll chime in on Discord during the week and I’ll download and give this a go, thank you!

**Comment by musicbynumbers** [comment]
Thanks for this.  :)
