### ISSUE TITLE
Unable to enter shift modified key input or numpad input

### ISSUE THREAD

**Issue by eleanorfontaine** [cycfi/ascend#9]
Ascend 1.0c
Win64
Reaper v6.18

I'm unable to enter either capital letters or symbols into the base field. In addition, Numpad entry no longer works (keyboard numbers work though).

Upon "Send all keyboard input to plugin" it works again though.

**Comment by djowel** [comment]
Confirmed

**Comment by djowel** [comment]
Fixed now in eval-1e
